CREATE DATABASE IF NOT EXISTS gestion_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE gestion_db;

CREATE TABLE IF NOT EXISTS budgets (
  id INT PRIMARY KEY,
  amount DECIMAL(12,2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE IF NOT EXISTS expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(255) NOT NULL,
  category VARCHAR(100) NOT NULL,
  amount DECIMAL(12,2) NOT NULL,
  date DATE NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
